language: node_js
node_js:
  - "10"
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: 1//09zn78I4eBMVSCgYIARAAGAkSNwF-L9IrirLJ6HIlq6swnOONKNn4OLV81Ol3kZ7k_8h2G3Xz7RMkkt8NeJ7O2_vhj-NG3dOOjdo
  message: "Automatically deployed through travis ci"
