language: node_js
node_js:
  - "10"
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: aidj+3Ww+dkvlIv2iZtJzlltn0CSOzzohAjybd/Pney4q64DGU0AgDEU5CnsBt3u5KrATbqqS2LPoKZohjx139KFb7Zyjwi+4g5cPHqBfMx/ai6YcJNeFBV7XUAl2wceRkYGQe3LJOfaayZ/G/4VHJ17qTRIeOMGJacPT2BVNRE/T+9whNsTq3+oQKrc+YixXvpJpK9MkWNzpy6TNfZITqmsPj9DXQoiWW8YbNM87dVHtCEFPiZRaAUtwJ+Hw2thAILyQUKXRqVQrrNN3IdXzRC+nZpaqo4Ehtu4wZuZivKHP2Q/whtNQnETXGc6Ibly7VaPO2DXL6wQiQHMxFZsFh4conBSv+2P7KpnmXVb7HCrMpcWXe9XIi9+A42rmUcCB/8hUUSXcZYCvG0WBPAqEvGEpXsbvEvuCwQHSbdEgexX9Wj/r2zSiBiza/aTrhucVOutuqefxXgF0ZDj6kxqurp2lp2Jv8qXyd20oQBKwpNrWch3moofLx22kZdbsDAxSKIAglcT+YMKDvzQvxHrzGzrblNP1TXG69ufe1vBdxjwmWQppIRiwmTklT7YLN7ZTXE/XD171Sj+n7iwp4A49Gd2oss+vPU3xteZW0qAP7NvNhZUAPb4AMcumcnL5BBmyFEh7f/TcXF7hwcCud/BTibjSKG5Jkq4cm0rJGrQ5ic=
  message: Automatically deployed through travis ci
